clc; clear; close all;
list_of_figures = { 'lin_flashing_cvs_alpha_flm_2in.fig',... % (1)
                    'lin_single_cvs_flm_4in.fig',...         % (2)
                    'nln_flashing_cvs_alpha_flm_2in.fig',...    % (3)
                    'nln_single_cvs_flm_4in.fig',...            % (4)
                    'lin_flashing_cvs_res_v_dt.fig',...      % (5)
                    'nln_flashing_cvs_res_v_dt.fig',...         % (6)
                    'lin_single_cvs_res_v_dt.fig',...        % (7)
                    'nln_single_cvs_res_v_dt.fig'};             % (8)
N = size(list_of_figures,2);

for i = 1:N
    f(i).handle = open(list_of_figures{i});
    f(i).kids = get(f(i).handle,'Children');
    f(i).data_kids = f(i).kids(size(f(i).kids,1)/2+1:end);
    for j = 1:size(f(i).data_kids,1)
        f(i).grandkids(j).id = get(f(i).data_kids(j),'Children');
        for k = 1:size(f(i).grandkids(j).id,1)
           f(i).grandkids(j).data(k).time=get(f(i).grandkids(j).id(k),'XData'); 
           f(i).grandkids(j).data(k).var=get(f(i).grandkids(j).id(k),'YData');
           f(i).grandkids(j).data(k).legend_entry = strcat('$',regexp(get(f(i).grandkids(j).id(k),'DisplayName'),'.*{','match'),'\mathrm{MAX}}$ ',regexp(get(f(i).grandkids(j).id(k),'DisplayName'),'=.*','match'));
        end
    end
end
%%
close all;
print_driver = 'psc2';
orientation = 'portrait';
%% flashing_1em1.eps
file_name = 'flashing_1em1.eps';
fig_id = 1;
figure(fig_id);

plot(   f(1).grandkids(2).data(5).time,f(1).grandkids(2).data(5).var,'- k',...
        f(3).grandkids(2).data(5).time,f(3).grandkids(2).data(5).var,'.-k'...
        )
axis([0 5 0.5 1])
ylabel('$\alpha_g$ [-] @ 2 [in] from Inlet','Interpreter','latex','FontSize',16)
xlabel('Time [s]','Interpreter','latex','FontSize',16)
legend('Linear Mode','Nonlinear Mode','best')

orient(fig_id, orientation)
saveas(fig_id, file_name, print_driver)
%% flashing_1em5.eps
file_name = 'flashing_1em5.eps';
fig_id = 2;
figure(fig_id)
plot(   f(1).grandkids(2).data(1).time,f(1).grandkids(2).data(1).var,'- k',...
        f(3).grandkids(2).data(1).time,f(3).grandkids(2).data(1).var,'.-k'...
        )
axis([0 5 0.5 1])
ylabel('$\alpha_g$ [-] @ 2 [in] from Inlet','Interpreter','latex','FontSize',16)
xlabel('Time [s]','Interpreter','latex','FontSize',16)
legend('Linear Mode','Nonlinear Mode','best')

orient(fig_id, orientation)
saveas(fig_id, file_name, print_driver)
%% lin_flashing_al_2in.eps
file_name = 'lin_flashing_al_2in.eps';
fig_id = 3;
figure(fig_id)
plot(...%   f(1).grandkids(2).data(6).time, f(1).grandkids(2).data(6).var,'-ok',...
        f(1).grandkids(2).data(5).time, f(1).grandkids(2).data(5).var,'-+k',...
        f(1).grandkids(2).data(4).time, f(1).grandkids(2).data(4).var,'-.k',...
        f(1).grandkids(2).data(3).time, f(1).grandkids(2).data(3).var,': k',...
        f(1).grandkids(2).data(2).time, f(1).grandkids(2).data(2).var,'--k',...
        f(1).grandkids(2).data(1).time, f(1).grandkids(2).data(1).var,'- k')
axis([0 5 0.5 1])
ylabel('$\alpha_g$ [-] @ 2 [in] from Inlet','Interpreter','latex','FontSize',16)
xlabel('Time [s]','Interpreter','latex','FontSize',16)
fleg = legend(...% char(f(1).grandkids(2).data(6).legend_entry),...
                char(f(1).grandkids(2).data(5).legend_entry),...
                char(f(1).grandkids(2).data(4).legend_entry),...
                char(f(1).grandkids(2).data(3).legend_entry),...
                char(f(1).grandkids(2).data(2).legend_entry),...
                char(f(1).grandkids(2).data(1).legend_entry),...
                'best');
set(fleg,'Interpreter','latex','FontSize',16)

orient(fig_id, orientation)
saveas(fig_id, file_name, print_driver)
%% cobra_flashing_al_2in.eps
% figure(33)
% plot(   f(1).grandkids(2).data(6).time, f(1).grandkids(2).data(6).var,...
%         f(1).grandkids(2).data(5).time, f(1).grandkids(2).data(5).var,...
%         f(1).grandkids(2).data(4).time, f(1).grandkids(2).data(4).var,...
%         f(1).grandkids(2).data(3).time, f(1).grandkids(2).data(3).var,...
%         f(1).grandkids(2).data(2).time, f(1).grandkids(2).data(2).var,...
%         f(1).grandkids(2).data(1).time, f(1).grandkids(2).data(1).var,'k')
% axis([0 5 0.5 1])
% ylabel('$\alpha_g$ [-] @ 2 [in] from Inlet','Interpreter','latex','FontSize',16)
% xlabel('Time [s]','Interpreter','latex','FontSize',16)
% fleg = legend( char(f(1).grandkids(2).data(6).legend_entry),...
%                 char(f(1).grandkids(2).data(5).legend_entry),...
%                 char(f(1).grandkids(2).data(4).legend_entry),...
%                 char(f(1).grandkids(2).data(3).legend_entry),...
%                 char(f(1).grandkids(2).data(2).legend_entry),...
%                 char(f(1).grandkids(2).data(1).legend_entry),...
%                 0);
% set(fleg,'Interpreter','latex','FontSize',16)
%% nl_flashing_al_2in.eps
% figure(44)
% plot(   f(3).grandkids(2).data(6).time, f(3).grandkids(2).data(6).var,...
%         f(3).grandkids(2).data(5).time, f(3).grandkids(2).data(5).var,...
%         f(3).grandkids(2).data(4).time, f(3).grandkids(2).data(4).var,...
%         f(3).grandkids(2).data(3).time, f(3).grandkids(2).data(3).var,...
%         f(3).grandkids(2).data(2).time, f(3).grandkids(2).data(2).var,...
%         f(3).grandkids(2).data(1).time, f(3).grandkids(2).data(1).var,'k')
% axis([0 5 0.5 1])
% ylabel('$\alpha_g$ [-] @ 2 [in] from Inlet','Interpreter','latex','FontSize',16)
% xlabel('Time [s]','Interpreter','latex','FontSize',16)
% fleg = legend( char(f(3).grandkids(2).data(6).legend_entry),...
%                 char(f(3).grandkids(2).data(5).legend_entry),...
%                 char(f(3).grandkids(2).data(4).legend_entry),...
%                 char(f(3).grandkids(2).data(3).legend_entry),...
%                 char(f(3).grandkids(2).data(2).legend_entry),...
%                 char(f(3).grandkids(2).data(1).legend_entry),0);
% set(fleg,'Interpreter','latex','FontSize',16)
%% nln_flashing_al_2in.eps
file_name = 'nln_flashing_al_2in.eps';
fig_id = 4;
figure(fig_id)
plot(   f(3).grandkids(2).data(6).time, f(3).grandkids(2).data(6).var,'-ok',...
        f(3).grandkids(2).data(5).time, f(3).grandkids(2).data(5).var,'-+k',...
        f(3).grandkids(2).data(4).time, f(3).grandkids(2).data(4).var,'-.k',...
        f(3).grandkids(2).data(3).time, f(3).grandkids(2).data(3).var,': k',...
        f(3).grandkids(2).data(2).time, f(3).grandkids(2).data(2).var,'--k',...
        f(3).grandkids(2).data(1).time, f(3).grandkids(2).data(1).var,'- k')
axis([0 5 0.5 1])
ylabel('$\alpha_g$ [-] @ 2 [in] from Inlet','Interpreter','latex','FontSize',16)
xlabel('Time [s]','Interpreter','latex','FontSize',16)
fleg = legend( char(f(3).grandkids(2).data(6).legend_entry),...
                char(f(3).grandkids(2).data(5).legend_entry),...
                char(f(3).grandkids(2).data(4).legend_entry),...
                char(f(3).grandkids(2).data(3).legend_entry),...
                char(f(3).grandkids(2).data(2).legend_entry),...
                char(f(3).grandkids(2).data(1).legend_entry),...
                'best');
set(fleg,'Interpreter','latex','FontSize',16)

orient(fig_id, orientation)
saveas(fig_id, file_name, print_driver)
%% nlm_flashing_1em0_1em1.eps
file_name = 'nln_flashing_1em0_1em1.eps';
fig_id = 5;
figure(fig_id)

plot(   f(3).grandkids(2).data(6).time, f(3).grandkids(2).data(6).var,': ',...
        f(3).grandkids(2).data(5).time, f(3).grandkids(2).data(5).var,'--',...
        f(3).grandkids(2).data(4).time, f(3).grandkids(2).data(4).var,'-.',...
        f(3).grandkids(2).data(3).time, f(3).grandkids(2).data(3).var,'--',...
        f(3).grandkids(2).data(2).time, f(3).grandkids(2).data(2).var,'- k'...
        )
axis([0 5 0.5 1])
ylabel('$\alpha_g$ [-] @ 2 [in] from Inlet','Interpreter','latex','FontSize',16)
xlabel('Time [s]','Interpreter','latex','FontSize',16)
fleg = legend(  char(f(3).grandkids(2).data(6).legend_entry),...
                char(f(3).grandkids(2).data(5).legend_entry),...
                char(f(3).grandkids(2).data(4).legend_entry),...
                char(f(3).grandkids(2).data(3).legend_entry),...
                char(f(3).grandkids(2).data(2).legend_entry),...
                'best');
set(fleg,'Interpreter','latex','FontSize',16)

orient(fig_id, orientation)
saveas(fig_id, file_name, print_driver)
%% lin_flashing_1em1_1em4.eps
file_name = 'lin_flashing_1em1_1em4.eps';
fig_id = 6;
figure(fig_id)

plot(   f(1).grandkids(2).data(5).time, f(1).grandkids(2).data(5).var,': k',...
        f(1).grandkids(2).data(4).time, f(1).grandkids(2).data(4).var,'-.k',...
        f(1).grandkids(2).data(3).time, f(1).grandkids(2).data(3).var,'--k',...
        f(1).grandkids(2).data(2).time, f(1).grandkids(2).data(2).var,'- k'...
        )
axis([0 5 0.5 1])
ylabel('$\alpha_g$ [-] @ 2 [in] from Inlet','Interpreter','latex','FontSize',16)
xlabel('Time [s]','Interpreter','latex','FontSize',16)
fleg = legend(  char(f(1).grandkids(2).data(5).legend_entry),...
                char(f(1).grandkids(2).data(4).legend_entry),...
                char(f(1).grandkids(2).data(3).legend_entry),...
                char(f(1).grandkids(2).data(2).legend_entry),...
                'best');
set(fleg,'Interpreter','latex','FontSize',16)

orient(fig_id, orientation)
saveas(fig_id, file_name, print_driver)
%% lin_flashing_res_compare.eps
file_name = 'lin_flashing_res_compare.eps';
fig_id = 7;

figure(fig_id)
plot(   f(5).grandkids(1).data(5).time, f(5).grandkids(1).data(5).var,'- k',...
        f(5).grandkids(1).data(1).time, f(5).grandkids(1).data(1).var,'--k'...
        )
axis([0 5 0 1])
ylabel('$\frac{||\mathbf{F}(\mathbf{x}^{1})||_2}{N}$ [-]','Interpreter','latex','FontSize',16)
xlabel('Time [s]','Interpreter','latex','FontSize',16)
fleg = legend(  char(f(5).grandkids(1).data(5).legend_entry),...
                char(f(5).grandkids(1).data(1).legend_entry),...
                'best');
set(fleg,'Interpreter','latex','FontSize',16)

orient(fig_id, orientation)
saveas(fig_id, file_name, print_driver)
%% nln_flashing_res_compare.eps
file_name = 'nln_flashing_res_compare.eps';
fig_id = 8;
figure(fig_id)

plot(   f(6).grandkids(1).data(5).time, f(6).grandkids(1).data(5).var,'- k',...
        f(6).grandkids(1).data(1).time, f(6).grandkids(1).data(1).var,'--k'...
        )
axis([0 5 0 1])
ylabel('$\frac{||\mathbf{F}(\mathbf{x}^{k})||_2}{N}$ [-]','Interpreter','latex','FontSize',16)
xlabel('Time [s]','Interpreter','latex','FontSize',16)
fleg = legend(  char(f(6).grandkids(1).data(5).legend_entry),...
                char(f(6).grandkids(1).data(1).legend_entry),...
                'best');
set(fleg,'Interpreter','latex','FontSize',16)

orient(fig_id, orientation)
saveas(fig_id, file_name, print_driver)
%% single_1em0.eps
file_name = 'single_1em0.eps';
fig_id = 9;
figure(fig_id)

plot(   f(2).grandkids(1).data(6).time,f(2).grandkids(1).data(6).var,'- k',...
        f(4).grandkids(1).data(6).time,f(4).grandkids(1).data(6).var,'-*k'...
        )
axis([0 5 0 1])
ylabel('$\dot{\mathrm{m}}_{\, l}$ [$\frac{\mathrm{lb}_{\mathrm{m}}}{\mathrm{s}}$] @ 4 [in] from Inlet','Interpreter','latex','FontSize',16)
xlabel('Time [s]','Interpreter','latex','FontSize',16)
legend('Linear Mode','Nonlinear Mode','best')

orient(fig_id, orientation)
saveas(fig_id, file_name, print_driver)
%% single_1em5.eps
file_name = 'single_1em5.eps';
fig_id = 10;
figure(fig_id)
plot(   f(2).grandkids(1).data(1).time,f(2).grandkids(1).data(1).var,'- k',...
        f(4).grandkids(1).data(1).time,f(4).grandkids(1).data(1).var,'-*k' ...
        )
axis([0 5 0 1])
ylabel('$\dot{\mathrm{m}}_{\, l}$ [$\frac{\mathrm{lb}_{\mathrm{m}}}{\mathrm{s}}$] @ 4 [in] from Inlet','Interpreter','latex','FontSize',16)
xlabel('Time [s]','Interpreter','latex','FontSize',16)
legend('Linear Mode','Nonlinear Mode','best')

orient(fig_id, orientation)
saveas(fig_id, file_name, print_driver)
%% single_1em3_zoom.eps
file_name = 'single_1em3_zoom.eps';
fig_id = 11;
figure(fig_id)
plot(   f(2).grandkids(1).data(3).time,f(2).grandkids(1).data(3).var,'- k',...
        f(4).grandkids(1).data(3).time,f(4).grandkids(1).data(3).var,'-*k'...
        )
axis([0.8 1.2 0 0.1])
ylabel('$\dot{\mathrm{m}}_{\, l}$ [$\frac{\mathrm{lb}_{\mathrm{m}}}{\mathrm{s}}$] @ 4 [in] from Inlet','Interpreter','latex','FontSize',16)
xlabel('Time [s]','Interpreter','latex','FontSize',16)
legend('Linear Mode','Nonlinear Mode','best')

orient(fig_id, orientation)
saveas(fig_id, file_name, print_driver)
%% single_1em3.eps
file_name = 'single_1em3.eps';
fig_id = 12;
figure(fig_id)
plot(   f(2).grandkids(1).data(3).time,f(2).grandkids(1).data(3).var,'- k',...
        f(4).grandkids(1).data(3).time,f(4).grandkids(1).data(3).var,'-*k'...
        )
axis([0 5 0 1])
ylabel('$\dot{\mathrm{m}}_{\, l}$ [$\frac{\mathrm{lb}_{\mathrm{m}}}{\mathrm{s}}$] @ 4 [in] from Inlet','Interpreter','latex','FontSize',16)
xlabel('Time [s]','Interpreter','latex','FontSize',16)
legend('Linear Mode','Nonlinear Mode','best')

orient(fig_id, orientation)
saveas(fig_id, file_name, print_driver)
%% lin_single_res_v_dt.eps
file_name = 'lin_single_res_v_dt.eps';
fig_id = 13;
figure(fig_id)
plot(   f(7).grandkids(1).data(6).time,f(7).grandkids(1).data(6).var,'-ok',...
        f(7).grandkids(1).data(5).time,f(7).grandkids(1).data(5).var,'-+k',...
        f(7).grandkids(1).data(4).time,f(7).grandkids(1).data(4).var,': k', ...
        f(7).grandkids(1).data(3).time,f(7).grandkids(1).data(3).var,'-.k',...
        f(7).grandkids(1).data(2).time,f(7).grandkids(1).data(2).var,'--k',...
        f(7).grandkids(1).data(1).time,f(7).grandkids(1).data(1).var,'- k' ...
        )
axis([0 5 0 1])
ylabel('$\frac{||\mathbf{F}(\mathbf{x}^{1})||_2}{N}$ [-]','Interpreter','latex','FontSize',16)
xlabel('Time [s]','Interpreter','latex','FontSize',16)
fleg = legend(  char(f(7).grandkids(1).data(6).legend_entry),...
                char(f(7).grandkids(1).data(5).legend_entry),...
                char(f(7).grandkids(1).data(4).legend_entry),...
                char(f(7).grandkids(1).data(3).legend_entry),...
                char(f(7).grandkids(1).data(2).legend_entry),...
                char(f(7).grandkids(1).data(1).legend_entry),...
                'best');
set(fleg,'Interpreter','latex','FontSize',16)

orient(fig_id, orientation)
saveas(fig_id, file_name, print_driver)
%% nln_single_res_v_dt.eps
file_name = 'nln_single_res_v_dt.eps';
fig_id = 14;
figure(fig_id)
plot(   f(8).grandkids(1).data(6).time,f(8).grandkids(1).data(6).var,'-+k',...
        f(8).grandkids(1).data(5).time,f(8).grandkids(1).data(5).var,'-*k',...
        f(8).grandkids(1).data(4).time,f(8).grandkids(1).data(4).var,': k', ...
        f(8).grandkids(1).data(3).time,f(8).grandkids(1).data(3).var,'-.k',...
        f(8).grandkids(1).data(2).time,f(8).grandkids(1).data(2).var,'--k',...
        f(8).grandkids(1).data(1).time,f(8).grandkids(1).data(1).var,'- k' ...
        )
axis([0 5 0 1])
ylabel('$\frac{||\mathbf{F}(\mathbf{x}^{k})||_2}{N}$ [-]','Interpreter','latex','FontSize',16)
xlabel('Time [s]','Interpreter','latex','FontSize',16)
fleg = legend(  char(f(8).grandkids(1).data(6).legend_entry),...
                char(f(8).grandkids(1).data(5).legend_entry),...
                char(f(8).grandkids(1).data(4).legend_entry),...
                char(f(8).grandkids(1).data(3).legend_entry),...
                char(f(8).grandkids(1).data(2).legend_entry),...
                char(f(8).grandkids(1).data(1).legend_entry),...
                'best');
set(fleg,'Interpreter','latex','FontSize',16)

orient(fig_id, orientation)
saveas(fig_id, file_name, print_driver)
%% nln_res_single_zoom.eps
file_name = 'nln_res_single_zoom.eps';
fig_id = 15;
figure(fig_id)
plot(   f(8).grandkids(1).data(6).time,f(8).grandkids(1).data(6).var,'-+k',...
        f(8).grandkids(1).data(5).time,f(8).grandkids(1).data(5).var,'-*k',...
        f(8).grandkids(1).data(4).time,f(8).grandkids(1).data(4).var,': k', ...
        f(8).grandkids(1).data(3).time,f(8).grandkids(1).data(3).var,'-.k',...
        f(8).grandkids(1).data(2).time,f(8).grandkids(1).data(2).var,'--k',...
        f(8).grandkids(1).data(1).time,f(8).grandkids(1).data(1).var,'- k' ...
        )
axis([.8 1.2 0 .1])
ylabel('$\frac{||\mathbf{F}(\mathbf{x}^{k})||_2}{N}$ [-]','Interpreter','latex','FontSize',16)
xlabel('Time [s]','Interpreter','latex','FontSize',16)
fleg = legend(  char(f(8).grandkids(1).data(6).legend_entry),...
                char(f(8).grandkids(1).data(5).legend_entry),...
                char(f(8).grandkids(1).data(4).legend_entry),...
                char(f(8).grandkids(1).data(3).legend_entry),...
                char(f(8).grandkids(1).data(2).legend_entry),...
                char(f(8).grandkids(1).data(1).legend_entry),...
                'best');
set(fleg,'Interpreter','latex','FontSize',16)

orient(fig_id, orientation)
saveas(fig_id, file_name, print_driver)
%% nln_flashing_semilogy_res_compare.eps
file_name = 'nln_flashing_semilogy_res_compare.eps';
fig_id = 16;
figure(fig_id)
semilogy(   f(6).grandkids(1).data(5).time, f(6).grandkids(1).data(5).var,'- k',...
            f(6).grandkids(1).data(1).time, f(6).grandkids(1).data(1).var,': k'...
        )
axis([0 5 1e-12 1])
ylabel('$\frac{||\mathbf{F}(\mathbf{x}^{k})||_2}{N}$ [-]','Interpreter','latex','FontSize',16)
xlabel('Time [s]','Interpreter','latex','FontSize',16)
fleg = legend(  char(f(6).grandkids(1).data(5).legend_entry),...
                char(f(6).grandkids(1).data(1).legend_entry),...
                'best');
set(fleg,'Interpreter','latex','FontSize',16)

orient(fig_id, orientation)
saveas(fig_id, file_name, print_driver)
%% lin_flashing_semilogy_res_compare.eps
file_name = 'lin_flashing_semilogy_res_compare.eps';
fig_id = 17;
figure(fig_id)
semilogy(   f(5).grandkids(1).data(5).time, f(5).grandkids(1).data(5).var,'-k',...
            f(5).grandkids(1).data(1).time, f(5).grandkids(1).data(1).var,':k'...
        )
axis([0 5 1e-12 1])
ylabel('$\frac{||\mathbf{F}(\mathbf{x}^{1})||_2}{N}$ [-]','Interpreter','latex','FontSize',16)
xlabel('Time [s]','Interpreter','latex','FontSize',16)
fleg = legend(  char(f(5).grandkids(1).data(5).legend_entry),...
                char(f(5).grandkids(1).data(1).legend_entry),...
                'best');
set(fleg,'Interpreter','latex','FontSize',16)

orient(fig_id, orientation)
saveas(fig_id, file_name, print_driver)
%% nln_single_semilogy_res_v_dt.eps
file_name = 'nln_single_semilogy_res_v_dt.eps';
fig_id = 18;
figure(fig_id)
semilogy(   f(8).grandkids(1).data(6).time,f(8).grandkids(1).data(6).var,'-ok',...
            f(8).grandkids(1).data(5).time,f(8).grandkids(1).data(5).var,'-*k',...
            f(8).grandkids(1).data(4).time,f(8).grandkids(1).data(4).var,': k', ...
            f(8).grandkids(1).data(3).time,f(8).grandkids(1).data(3).var,'-.k',...
            f(8).grandkids(1).data(2).time,f(8).grandkids(1).data(2).var,'--k',...
            f(8).grandkids(1).data(1).time,f(8).grandkids(1).data(1).var,'- k' ...
            )
axis([0 5 1e-12 1])
ylabel('$\frac{||\mathbf{F}(\mathbf{x}^{k})||_2}{N}$ [-]','Interpreter','latex','FontSize',16)
xlabel('Time [s]','Interpreter','latex','FontSize',16)
fleg = legend(  char(f(8).grandkids(1).data(6).legend_entry),...
                char(f(8).grandkids(1).data(5).legend_entry),...
                char(f(8).grandkids(1).data(4).legend_entry),...
                char(f(8).grandkids(1).data(3).legend_entry),...
                char(f(8).grandkids(1).data(2).legend_entry),...
                char(f(8).grandkids(1).data(1).legend_entry),...
                'best');
set(fleg,'Interpreter','latex','FontSize',16)

orient(fig_id, orientation)
saveas(fig_id, file_name, print_driver)
%% lin_single_semilogy_res_v_dt.eps
file_name = 'lin_single_semilogy_res_v_dt.eps';
fig_id = 19;
figure(fig_id)
semilogy(   f(7).grandkids(1).data(6).time,f(7).grandkids(1).data(6).var,'-ok',...
            f(7).grandkids(1).data(5).time,f(7).grandkids(1).data(5).var,'-*k',...
            f(7).grandkids(1).data(4).time,f(7).grandkids(1).data(4).var,': k', ...
            f(7).grandkids(1).data(3).time,f(7).grandkids(1).data(3).var,'-.k',...
            f(7).grandkids(1).data(2).time,f(7).grandkids(1).data(2).var,'--k',...
            f(7).grandkids(1).data(1).time,f(7).grandkids(1).data(1).var,'- k'  ...
            )
axis([0 5 1e-12 1])
ylabel('$\frac{||\mathbf{F}(\mathbf{x}^{1})||_2}{N}$ [-]','Interpreter','latex','FontSize',16)
xlabel('Time [s]','Interpreter','latex','FontSize',16)
fleg = legend(  char(f(7).grandkids(1).data(6).legend_entry),...
                char(f(7).grandkids(1).data(5).legend_entry),...
                char(f(7).grandkids(1).data(4).legend_entry),...
                char(f(7).grandkids(1).data(3).legend_entry),...
                char(f(7).grandkids(1).data(2).legend_entry),...
                char(f(7).grandkids(1).data(1).legend_entry),...
                'best');
set(fleg,'Interpreter','latex','FontSize',16)

orient(fig_id, orientation)
saveas(fig_id, file_name, print_driver)
%%